Задание 1
Создайте numpy array с элементами от числа N до 0. Например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [59]:
N=int(input('Введите число N '))
list_1=np.arange(N, 0, -1)             #1 Вариант, встроенная функция 
list_1

Введите число N 10


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [60]:
list_2=np.asarray(list(range(N, 0, -1)))    #2 Вариант, сначала обычный список, потом преобразование
list_2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму её значений на диагонали

In [76]:
N1=int(input('Введите количество элементов на диагонали '))
matr=np.diag(np.arange(N1, 0, -1), k=0)
print(matr)
np.sum(matr)

Введите количество элементов на диагонали 8
[[8 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0]
 [0 0 0 5 0 0 0 0]
 [0 0 0 0 4 0 0 0]
 [0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 1]]


36

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [77]:
from numpy import linalg

In [102]:
# коэффициенты при переменных в левой части уравнения
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

# значения в правой части уравнения
b = np.array( [4, 12, -3] )

In [103]:
out=linalg.solve(a, b)
out

array([ 0.46666667,  3.84444444, -5.55555556])

In [104]:
np.allclose( np.dot(a, ([ 0,  3, -5])), b, 0.5 ) # для экспериментам подставим любые свои числа. Ответ "ложь", значит элементы двух массивов не равны (погрешность более заданной 0.5)

False

In [105]:
# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4
Задание и входные данные к нему находятся в материалах занятия: ноутбук к лекции «Библиотека NumPy. Вычислительные задачи» ---- Python_9_Numpy.ipynb ---- Косинусное сходство между векторами ---- Задача 4 домашнего задания.

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [3]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [4]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [7]:
list_=[]
for el in users_stats:
    list_.append(cosine(next_user_stats,el))
print(list_)

[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]


In [34]:
print('Минимальный косинус/наиболее похожий клиент =', cos_i)
print('ID пользователей с минимальным косинусом/самые похожие клиенты')
i=0
for cos_i in list_:
    if cos_i == min(list_):
        print(i+1)
    i +=1

Минимальный косинус/наиболее похожий клиент = 0.0
ID пользователей с минимальным косинусом/самые похожие клиенты
6
7
9
10
